name: Notion2Github
on:
  workflow_dispatch:
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@v1.1.1
        with:
          database-url: 'https://www.notion.so/4081964150024719ac433b4dd0b770fa'
          docs-directory: docs
        env:
          NOTION_TOKEN: ${{ secrets.TOKEN_NOTION }}

      - name: Update npm packages
        uses: technote-space/create-pr-action@v2
        with:
         COMMIT_MESSAGE: 'notion: Update docs (auto)'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'example@example.com'
         PR_BRANCH_NAME: 'notion-docs-update-${PR_ID}'
         PR_TITLE: 'Notion: update docs'

#       - name: Format documents
#         uses: creyD/prettier_action@v3.1
#         with:
#           prettier_options: --write ./docs/**/*.md
#           commit_message: 'notion: Update docs (auto)'
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
