name: Notion to Github Direct Commit
on:
  workflow_dispatch:
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@main
        with:
          database-url: https://www.notion.so/4081964150024719ac433b4dd0b770fa
          docs-directory: notion-docs
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./notion-docs/**/*.md
          commit_message: 'notion-docs: Update notion-docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
