name: Notion to Github -- Create PR
on:
  workflow_dispatch:
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@main
        with:
          database-url: https://www.notion.so/4081964150024719ac433b4dd0b770fa
          docs-directory: notion-docs
        env:
          NOTION_TOKEN: ${{ secrets.TOKEN_NOTION }}

      - name: Reduce Header Levels
        run: npm run reduce-md-headers

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Notion - Update docs
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          # branch: notion-update-docs-2
          delete-branch: true
          title: '[Notion] Update docs'
