name: Notion2Github
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@v1.1.0
        with:
          database-url: 'https://www.notion.so/e59174dc88f64f87a36f08853ca97e0b'
          docs-directory: markdowns
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./markdowns/**/*.md
          commit_message: 'notion: Update docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}